// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKrK-yRoJSVej73KDTKrAIGOsU8jfTHw',
    appId: '1:670650475162:web:8b2fbaea6c239566e77523',
    messagingSenderId: '670650475162',
    projectId: 'constructionlk-95bab',
    authDomain: 'constructionlk-95bab.firebaseapp.com',
    storageBucket: 'constructionlk-95bab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2Qm9ox4tc_mdnc118wK1pYt1BBFCMDI',
    appId: '1:670650475162:android:b4d6de1cd2ecf915e77523',
    messagingSenderId: '670650475162',
    projectId: 'constructionlk-95bab',
    storageBucket: 'constructionlk-95bab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7o5pLYoO8m_XOMAc9SjJWJUs984bvUbE',
    appId: '1:670650475162:ios:3bf3a26ea3b0668ae77523',
    messagingSenderId: '670650475162',
    projectId: 'constructionlk-95bab',
    storageBucket: 'constructionlk-95bab.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7o5pLYoO8m_XOMAc9SjJWJUs984bvUbE',
    appId: '1:670650475162:ios:3bf3a26ea3b0668ae77523',
    messagingSenderId: '670650475162',
    projectId: 'constructionlk-95bab',
    storageBucket: 'constructionlk-95bab.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVKrK-yRoJSVej73KDTKrAIGOsU8jfTHw',
    appId: '1:670650475162:web:d33e311b39f88940e77523',
    messagingSenderId: '670650475162',
    projectId: 'constructionlk-95bab',
    authDomain: 'constructionlk-95bab.firebaseapp.com',
    storageBucket: 'constructionlk-95bab.firebasestorage.app',
  );
}
